version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: npm run test:ci
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
