version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  test:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: npm install
      - run: npm run test:ci
workflows:
  version: 2
  test:
    jobs:
      - test
