version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    executor:
      name: node/default
      tag: '12.16.2'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test:ci
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
